# # updated dvc.yaml

# stages:
#   data_ingestion:
#     cmd: python src/data/data_ingestion.py
#     deps:
#     - mlops-mini-project/src/data/data_ingestion.py
#     params:
#     - data_ingestion.test_size
#     outs:
#     - mlops-mini-project/data/raw

#   data_preprocessing:
#     cmd: python mlops-mini-project/src/data/data_preprocessing.py
#     deps:
#     - mlops-mini-project/data/raw
#     - mlops-mini-project/src/data/data_preprocessing.py
#     outs:
#     - data/interim

#   feature_engineering:
#     cmd: python mlops-mini-project/src/features/feature_engineering.py
#     deps:
#     - mlops-mini-project/data/interim
#     - mlops-mini-project/src/features/feature_engineering.py
#     params:
#     - feature_engineering.max_features
#     outs:
#     - mlops-mini-project/data/processed
#     - mlops-mini-project/models/vectorizer.pkl

#   model_building:
#     cmd: python mlops-mini-project/src/model/model_building.py
#     deps:
#     - mlops-mini-project/data/processed
#     - mlops-mini-project/src/model/model_building.py
#     outs:
#     - mlops-mini-project/models/model.pkl

#   model_evaluation:
#     cmd: python mlops-mini-project/src/model/model_evaluation.py
#     deps:
#     - mlops-mini-project/models/model.pkl
#     - mlops-mini-project/src/model/model_evaluation.py
#     metrics:
#     - mlops-mini-project/reports/metrics.json
#     outs:
#     - mlops-mini-project/reports/experiment_info.json  # Add the model_info.json file as an output
# --------------------------------------------------------------------------------------------------------
  # model_registration:
  #   cmd: python mlops-mini-project/src/model/register_model.py
  #   deps:
  #   - mlops-mini-project/reports/experiment_info.json
  #   - mlops-mini-project/src/model/register_model.py


  # updated dvc.yaml

stages:
  data_ingestion:
    cmd: python src/data/data_ingestion.py
    deps:
    - src/data/data_ingestion.py
    params:
    - data_ingestion.test_size
    outs:
    - data/raw

  data_preprocessing:
    cmd: python src/data/data_preprocessing.py
    deps:
    - data/raw
    - src/data/data_preprocessing.py
    outs:
    - data/interim

  feature_eng:
    cmd: python src/features/feature_eng.py
    deps:
    - data/interim
    - src/features/feature_eng.py
    params:
    - feature_eng.max_features
    outs:
    - data/processed
    - models/vectorizer.pkl

  model_building:
    cmd: python src/model/model_building.py
    deps:
    - data/processed
    - src/model/model_building.py
    outs:
    - models/model.pkl

  model_evaluation:
    cmd: python src/model/model_evaluation.py
    deps:
    - models/model.pkl
    - src/model/model_evaluation.py
    metrics:
    - reports/metrics.json
    outs:
    - reports/experiment_info.json  # Add the model_info.json file as an output

  # model_registration:
  #   cmd: python src/model/register_model.py
  #   deps:
  #   - reports/experiment_info.json
  #   - src/model/register_model.py